/*
 Generated by typeshare 1.0.0
*/

export interface Player {
	hand: Cards;
	books: Ranks;
}

export interface Game {
	starting_cards: number;
	pool: Cards;
	players: Player[];
	announcements: Announcement[];
	stage: GameStage;
}

export type GameStage = 
	| { name: "Dealing", content: {
	who_next: PlayerId;
}}
	| { name: "Playing", content: {
	who_next: PlayerId;
}}
	| { name: "Done", content: {
	who_next: PlayerId;
}};

export type Announcement = 
	| { type: "Action", content: {
	player_asking: PlayerId;
	player_asked: PlayerId;
	asked_for: Rank;
	response: Response;
}}
	| { type: "GotBook", content: {
	player: PlayerId;
	book: Rank;
}};

export type Response = 
	| { type: "GoFish", content?: undefined }
	| { type: "TakeThese", content: {
	count: number;
}};

